name: Test

on:
  push:
      paths:
        - "**.mcfunction"
        - "**.json"

jobs:
  mc-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Check minecraft commands
        uses: mcbeet/check-commands@v1
        with:
          source: /home/runner/work/Minecraft-Rebalanced/Minecraft-Rebalanced
          minecraft: "1.19"
          stats: true

  json:
    runs-on: ubuntu-latest
    steps:
      - name: Install jsonlint
        run: npm install -g jsonlint
      - name: Lint json files
        run: for file in $(find . -name "*.json"); do jsonlint $file -c -q; done
